### ISSUE TITLE
What is Default `releaseRules` for "preset": "conventionalcommits" ?

### ISSUE THREAD

**Issue by patsevanton** [semantic-release/commit-analyzer#332]
Hello! Semantic-release is awesome project for release management! 
I try use semantic-release in project https://github.com/patsevanton/terraform-yandex-compute
.releaserc.json - [here ](https://github.com/patsevanton/terraform-yandex-compute/blob/main/.releaserc.json)

I created [PR](https://github.com/patsevanton/terraform-yandex-compute/pull/14) with message: "breaking: ...."
But version not changed.

I think i write bad code. 
My question:
What is Default `releaseRules` for "preset": "conventionalcommits" ?

Default `releaseRules` for "preset": "conventionalcommits" don`t have here: 
https://github.com/semantic-release/commit-analyzer/blob/master/lib/default-release-rules.js

**Comment by patsevanton** [comment]
I use ESLint
my .releaserc.json
```
{
  "branches": [
    "main",
    "master"
  ],
  "ci": false,
  "plugins": [
    [
      "@semantic-release/commit-analyzer",
      {
        "preset": "ESLint",
        "releaseRules": [
          {"tag": "breaking", "release": "major"},
          {"tag": "chore", "release": false},
          {"tag": "ci", "release": false},
          {"tag": "docs", "release": false},
          {"tag": "feat", "release": "minor"},
          {"tag": "fix", "release": "patch"},
          {"tag": "refactor", "release": "patch"},
          {"tag": "security", "release": "patch"},
          {"tag": "style", "release": "patch"},
          {"tag": "test", "release": false}
        ]
      }
    ],
    [
      "@semantic-release/release-notes-generator",
      {
        "preset": "ESLint"
      }
    ],
    [
      "@semantic-release/github",
      {
        "successComment": "This ${issue.pull_request ? 'PR is included' : 'issue has been resolved'} in version ${nextRelease.version} :tada:",
        "labels": true,
        "releasedLabels": true
      }
    ],
    [
      "@semantic-release/changelog",
      {
        "changelogFile": "CHANGELOG.md"
      }
    ],
    "@semantic-release/github",
    [
      "@semantic-release/git", {
      "assets": ["CHANGELOG.md"],
      "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    }
    ]
  ]
}
```

Part of readme
```
## Contributing

The following guidelines must be followed by all contributors to this repository. Please review them carefully and do not hesitate to ask for help.

### Type

The *type* should always be lowercase as shown below.

#### Allowed `<type>` values:

* **breaking: msg** (a commit that has the text BREAKING CHANGE: at the beginning of its optional body or footer section introduces a breaking API change)
* **chore: msg** (updating build/env/packages, etc; no production code change)
* **ci: msg** (changes to our CI configuration files and scripts )
* **docs: msg** (changes to documentation)
* **feat: msg** (new feature for the user)
* **fix: msg** (bug fix for the user, not a fix to build scripts)
* **refactor: msg** (refactoring production code, eg. renaming a variable)
* **security: msg** (fix security vulnerabilities)
* **style: msg** (formatting, missing semi colons, etc; no functional code change)
* **test: msg** (adding missing tests, refactoring tests; no production code change)
```

Github action release.yml
```
name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - '**/*.tpl'
      - '**/*.py'
      - '**/*.tf'
      - '.github/workflows/release.yml'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # Skip running release workflow on forks
    if: github.repository_owner == 'patsevanton'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@4.6.3
            conventional-changelog-eslint@3.0.9
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

```
