### ISSUE TITLE
This plugin just silently quits

### ISSUE THREAD

**Issue by stoopidJSON** [semantic-release/commit-analyzer#523]
This was working and now it just stopped. When my previously working pipelines run everything works as it did until this plugin starts...then it just ends. No error, and it even shows that it ran successfully, but no commits are analyzed and no action is taken. 

this is my releaserc.yaml
```
preset: conventionalcommits
tagFormat: "v${version}"

branches:
  - +([0-9])?(.{+([0-9]),x).x}
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/npm"
  - "@semantic-release/git"

verifyConditions:
  - "@semantic-release/changelog"
  - "@semantic-release/npm"
  - "@semantic-release/git"

analyzeCommits:
  - path: "@semantic-release/commit-analyzer"

generateNotes:
  - path: "@semantic-release/release-notes-generator"

prepare:
  - path: "@semantic-release/changelog"
    changelogFile: "CHANGELOG.md"
  - path: "@semantic-release/npm"
  - path: "@semantic-release/git"
```

I am running this in Jenkins via docker so it runs like this:
```
                            git config --global --add safe.directory ${WORKSPACE}
                            git config --global user.email "${userEmail}"
                            git config --global user.name "${userName}"
                            export GH_TOKEN=${GH_TOKEN}
                            export GH_URL=https://github.*****/api/v3 
                            npx semantic-release --debug
```

Now there are a lot of backed up commits (25) since this started silently failing so I'm not going to put the entire output here, but here's what I mean by silently failing/stopping:

```
[6:08:23 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
```

I'm tearing my hair out debugging...any advice, guidance, or help would be greatly appreciated!
